# This is a complete TDB configuration template which is always kept updated
# to include all the configuration options. I encourage you to always use this
# when you use a configuration file
# Instead of deleting entire sections from this file, comment them out, so that you
# now what you've kept enabled and what you've kept disabled. This helps avoid
# configuration problems during production

# This is a *REQUIRED* key
[server]
host = "127.0.0.1" # The IP address to which you want TDB to bind to
port = 2003 # The port to which you want TDB to bind to
# Set `noart` to true if you want to disable terminal artwork
noart = false

# This key is *OPTIONAL*, but will be required post 0.5.1
[bgsave]
# Run `BGSAVE` `every` seconds. For example, setting this to 60 will cause BGSAVE to run
# after every 2 minutes
enabled = true
every = 120

# This key is *OPTIONAL*
[snapshot]
every = 3600 # Make a snapshot after every 1 hour (60min * 60sec= 3600secs)
atmost = 4 # Keep the 4 most recent snapshots
