[package]
name = "skysh"
version = "0.7.1"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal deps
libsky = { path = "../libsky" }
skytable = { git = "https://github.com/skytable/client-rust", branch = "next", features = [
    "async",
    "aio-sslv",
], default-features = false }
# external deps
tokio = { version = "1.13.0", features = ["full"] }
clap = { version = "2.33.3", features = ["yaml"] }
rustyline = "9.0.0"
crossterm = "0.22.1"
