[package]
name = "skysh"
version = "0.7.3-alpha.3"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal deps
libsky = { path = "../libsky" }
skytable = { git = "https://github.com/skytable/client-rust", branch = "next", features = [
    "aio",
    "aio-sslv",
], default-features = false }
# external deps
tokio = { version = "1.16.1", features = ["full"] }
clap = { version = "2", features = ["yaml"] }
rustyline = "9.1.2"
crossterm = "0.23.0"
