[package]
name = "skysh"
version = "0.5.1"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsky = {path = "../libsky"}
tokio = {version = "1.5.0", features = ["full"]}
bytes = "1.0.1"
clap = {version = "2.33.3", features=["yaml"]}
openssl = { version = "0.10.33", features = ["vendored"] }
tokio-openssl = "0.6.1"
crossterm = "0.19.0"