[package]
name = "tsh"
version = "0.4.5-alpha.2"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libtdb = {path = "../libtdb"}
tokio = {version = "0.3.2", features = ["full"]}
bytes = "0.6.0"
regex = "1.4.1"
lazy_static = "1.4.0"
