[package]
name = "libstress"
version = "0.1.0"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# external deps
num_cpus = "1.13.0"
crossbeam-channel = "0.5.1"
rayon = "1.5.1"
log = "0.4.14"
rand = "0.8.4"
