[package]
name = "skyd"
version = "0.7.0"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
# internal deps
skytable = { git = "https://github.com/skytable/client-rust", branch = "next", default-features = false }
sky_macros = { path = "../sky-macros" }
libsky = { path = "../libsky" }
# external deps
tokio = { version = "1.9.0", features = ["full"] }
ahash = "0.7.4"
bytes = "1.0.1"
serde = { version = "1.0.127", features = ["derive"] }
toml = "0.5.8"
clap = { version = "2.33.3", features = ["yaml"] }
env_logger = "0.9.0"
log = "0.4.14"
chrono = "0.4.19"
regex = "1.5.4"
tokio-openssl = "0.6.2"
openssl = { version = "0.10.35", features = ["vendored"] }
hashbrown = { version = "0.11.2", features = ["raw"] }
parking_lot = "0.11.1"
num_cpus = "1.13.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
# external deps
jemallocator = "0.3.2"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version = "0.3.9", features = ["fileapi"] }

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.69"

[dev-dependencies]
# internal deps
libstress = { path = "../libstress" }
skytable = { git = "https://github.com/skytable/client-rust", features = [
    "async",
    "aio-ssl",
], default-features = false, branch = "next" }
# external deps
tokio = { version = "1.9.0", features = ["test-util"] }
rand = "0.8.4"
bincode = "1.3.3"
[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.99"
