[package]
name = "tdb"
version = "0.5.0"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.6", features = ["full"] }
bytes = "0.6.0"
libtdb = {path ="../libtdb"}
bincode = "1.3.1"
parking_lot = "0.11.1"
lazy_static = "1.4.0"
serde_derive = "1.0.117"
serde = {version = "1.0.118", features= ["derive"]}
toml = "0.5.7"
clap = {version = "2.33.3", features=["yaml"]}
env_logger = "0.8.2"
log = "0.4.11"
chrono = "0.4.19"
regex = "1.4.2"
tdb_macros = {path="../tdb-macros"}
tokio-openssl-vendored = {git="https://github.com/terrabasedb/tokio-openssl-vendored.git", branch="next"}
openssl = "0.10.31"
openssl-sys = "0.9.59"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
tokio = { version = "0.3.6", features = ["test-util"] }
