[package]
name = "skyd"
version = "0.6.1"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
# internal deps
skytable = { git = "https://github.com/skytable/client-rust", branch = "next", default-features = false }
# external deps
tokio = { version = "1.6.1", features = ["full"] }
bytes = "1.0.1"
libsky = { path = "../libsky" }
bincode = "1.3.3"
parking_lot = "0.11.1"
lazy_static = "1.4.0"
dashmap = {version = "4.0.2", features = ["serde"]}
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"
clap = { version = "2.33.3", features = ["yaml"] }
env_logger = "0.8.3"
log = "0.4.14"
chrono = "0.4.19"
regex = "1.5.4"
tokio-openssl = "0.6.1"
openssl = { version = "0.10.34", features = ["vendored"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
# external deps
jemallocator = "0.3.2"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version = "0.3.9", features = ["fileapi"] }

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.68"

[dev-dependencies]
# internal deps
sky_macros = { path = "../sky-macros" }
skytable = { git = "https://github.com/skytable/client-rust", features = ["async"], default-features = false, branch = "next" }
devtimer = "4.0.1"
# external deps
tokio = { version = "1.6.1", features = ["test-util"] }

[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.96"
