[package]
name = "skyd"
version = "0.6.3"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
# internal deps
skytable = { git="https://github.com/skytable/client-rust", branch="next", default-features=false }
sky_macros = { path="../sky-macros" }
# external deps
tokio = { version="1.7.0", features=["full"] }
bytes = "1.0.1"
libsky = { path="../libsky" }
bincode = "1.3.3"
lazy_static = "1.4.0"
dashmap = { version="4.0.2", features=["serde", "raw-api"] }
serde = { version="1.0.126", features=["derive"] }
toml = "0.5.8"
clap = { version="2.33.3", features=["yaml"] }
env_logger = "0.8.4"
log = "0.4.14"
chrono = "0.4.19"
regex = "1.5.4"
tokio-openssl = "0.6"
openssl = { version="0.10.34", features=["vendored"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
# external deps
jemallocator = "0.3.2"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version="0.3.9", features=["fileapi"] }

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.68"

[dev-dependencies]
# internal deps
libstress = { path="../libstress" }
skytable = { git="https://github.com/skytable/client-rust", features=["async", "aio-ssl"], default-features=false, branch="next" }
# external deps
tokio = { version="1.6.1", features=["test-util"] }
rand = "0.8.4"
[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.96"
