[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
build = "build.rs"
edition = "2021"
name = "skyd"
version = "0.8.0"

[dependencies]
# internal deps
libsky = { path = "../libsky" }
sky_macros = { path = "../sky-macros" }
# external deps
ahash = "0.7.6"
bytes = "1.1.0"
chrono = "0.4.19"
clap = { version = "2", features = ["yaml"] }
env_logger = "0.9.0"
hashbrown = { version = "0.12.2", features = ["raw"] }
log = "0.4.17"
openssl = { version = "0.10.40", features = ["vendored"] }
parking_lot = "0.12.1"
regex = "1.6.0"
serde = { version = "1.0.138", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
tokio-openssl = "0.6.3"
toml = "0.5.9"
rcrypt = "0.4.0"
base64 = "0.13.0"

[target.'cfg(all(not(target_env = "msvc"), not(miri)))'.dependencies]
# external deps
jemallocator = "0.5.0"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version = "0.3.9", features = ["fileapi"] }

[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.126"

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.73"

[dev-dependencies]
# internal deps
libstress = { path = "../libstress" }
skytable = { git = "https://github.com/skytable/client-rust", features = [
  "aio",
  "aio-ssl",
], default-features = false, branch = "next" }
# external deps
bincode = "1.3.3"
rand = "0.8.5"
tokio = { version = "1.19.2", features = ["test-util"] }

[features]
nightly = []
persist-suite = []

[package.metadata.deb]
name = "skytable"
maintainer = "Sayan Nandan <nandansayan@outlook.com>"
copyright = "2022, Sayan Nandan <nandansayan@outlook.com>"
license-file = ["../LICENSE", "0"]
maintainer-scripts = "../pkg/debian/"
extended-description-file = "pkg/debian/description.txt"
depends = "$auto"
section = "database"
priority = "optional"
assets = [
  [
    "target/release/skyd",
    "usr/bin/",
    "755",
  ],
  [
    "target/release/skysh",
    "usr/bin/",
    "755",
  ],
  [
    "target/release/sky-bench",
    "usr/bin/",
    "755",
  ],
  [
    "../pkg/common/skyd.service",
    "/etc/systemd/system/skyd.service",
    "644",
  ],
]
