[package]
name = "sky-bench"
version = "0.6.1"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal deps
skytable = { git="https://github.com/skytable/client-rust", branch="next" }
libsky = { path="../libsky" }
libstress = { path="../libstress" }
# external deps
rand = "0.8.3"
devtimer = "4.0.1"
clap = { version="2.33.3", features=["yaml"] }
serde = { version="1.0.126", features=["derive"] }
serde_json = "1.0.64"
rayon = "1.5.1"
