[package]
name = "libtdb"
version = "0.5.0-alpha.2"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bytes = "0.6.0"
termcolor = "1.1.0"