[package]
name = "libsky"
version = "0.5.1"
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bytes = "1.0.1"
termcolor = "1.1.2"
regex = "1.4.6"